version: '3.8'

services:
  postgres:
    container_name: virtual_gym_db
    image: postgres:14.6
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=virtual_gym_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres

  pgadmin:
    container_name: 'gym_pgadmin_service'
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=estefaniaprieto27@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
        - 127.0.0.1:5050:80
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin'
    networks:
      default:
        aliases:
          - pgadmin

networks:
  default:
    driver: bridge
volumes:
  pgadmin_data: